/**
 *
 * Copyrights
 *
 * Portions created or assigned to Cisco Systems, Inc. are
 * Copyright (c) 2011 Cisco Systems, Inc.  All Rights Reserved.
 */
/*build/dist/VTG-CAXL-release-8.6.1/src/jabberwerx.cisco.js*/
;(function(){var jabberwerx=window.jabberwerx;if(!jabberwerx){throw new Error("jabberwerx not defined. jabbwerwerx.cisco extension could not load");return;}
if('cisco'in jabberwerx){throw new Error("jabbwerwerx.cisco extension is already defined. Most likely a programatic error");return;}
jabberwerx.cisco={version:'8.6.1',_config:{},_init:function(){this._inited=true;}};jabberwerx.$.extend(jabberwerx.xhtmlim.allowedTags,{caption:["style"],table:["style","border","cellpadding","cellspacing","frame","summary","width"],td:["style","align","char","charoff","valign","abbr","axis","colspan","headers","rowspan","scope"],th:["style","abbr","axis","colspan","headers","rowspan","scope"],tr:["style","align","char","charoff","valign"],col:["style","align","char","charoff","valign","span","width"],colgroup:["style","align","char","charoff","valign","span","width"],tbosy:["style","align","char","charoff","valign"],thead:["style","align","char","charoff","valign"],tfoot:["style","align","char","charoff","valign"]});jabberwerx.cisco._init();window.jabberwerx.cisco=jabberwerx.cisco;})();
/*build/dist/VTG-CAXL-release-8.6.1/src/controller/QuickContactController.js*/
;(function(){if(jabberwerx&&jabberwerx.cisco){jabberwerx.cisco.QuickContactController=jabberwerx.Controller.extend({init:function(client){this._super(client,"quickContact");this.client.event('afterMessageReceived').bindWhen('message[type="headline"] event[xmlns="http://jabber.org/protocol/pubsub#event"] items[node="http://webex.com/connect/temp-presence"]>item>presence',this.invocation('_presenceReceived'));this.client.event("clientStatusChanged").bind(this.invocation("_handleStatusChange"));jabberwerx.globalEvents.bind("resourcePresenceChanged",this.invocation("_handleResourcePresenceUpdate"));this.client.entitySet.event('entityUpdated').bind(this.invocation('_handleEntityUpdated'));this.client.entitySet.event('entityRemoved').bind(this.invocation('_handleEntityRemoved'));},destroy:function(){var client=this.client;client.event("afterMessageReceived").unbind(this.invocation("_presenceReceived"));client.event("clientStatusChanged").unbind(this.invocation("_handleStatusChange"));jabberwerx.globalEvents.unbind("resourcePresenceChanged",this.invocation("_handleResourcePresenceUpdate"));client.entitySet.event('entityUpdated').unbind(this.invocation('_handleEntityUpdated'));client.entitySet.event('entityRemoved').unbind(this.invocation('_handleEntityRemoved'));this._super();},subscribe:function(jid){jid=jabberwerx.JID.asJID(jid).getBareJID();delete this._pendingSubs[jid.toString()];delete this._pendingUnsubs[jid.toString()];var entity=this.client.entitySet.entity(jid);if(entity&&entity instanceof(jabberwerx.RosterContact)&&(entity.properties.subscription=="both"||entity.properties.subscription=="to")){throw new TypeError("Can't add roster contact as a quick contact.");}
if(!entity||(entity instanceof jabberwerx.TemporaryEntity)){var quick=new jabberwerx.cisco.QuickContact(jid,this);if(entity){quick.apply(entity);entity.remove();entity=quick;}
entity=quick;entity.properties.temp_sub=true;this.client.entitySet.register(entity);}else{entity.properties.temp_sub=true;this.client.entitySet.event("entityUpdated").trigger(entity);}
if(!entity.getPrimaryPresence()){var pres=new jabberwerx.Presence();pres.setFrom(entity.jid);pres.setType("unavailable");entity.updatePresence(pres);}
var retVal=this.client.controllers.capabilities.addFeatureToJid(jid,'http://webex.com/connect/temp-presence+notify');return retVal;},subscribeAll:function(jids,reset){if(!jabberwerx.util.isArray(jids)){throw new TypeError("jids must be an array");}
if((reset!==undefined)&&reset){var that=this;jabberwerx.$.each(this.client.entitySet.toArray(),function(){if((this.properties.temp_sub!==undefined)&&(!that._pendingUnsubs.hasOwnProperty(this.jid))){that._pendingUnsubs[this.jid]=true;}});}
for(var i=0;i<jids.length;++i){try{var tjid=jabberwerx.JID.asJID(jids[i]).getBareJIDString();}catch(ex){jabberwerx.util.debug.warn("Skipping "+jids[i]+", could not parse JID");continue;}
if(this._pendingUnsubs.hasOwnProperty(tjid)){delete this._pendingUnsubs[tjid];}
var entity=this.client.entitySet.entity(tjid);if(entity&&(entity.properties.temp_sub!==undefined)){continue;}
if(this._pendingSubs.hasOwnProperty(tjid)){continue;}
this._pendingSubs[tjid]=true;}
if(!this._pendingTimer){this._processPending();}},unsubscribe:function(jid){jid=jabberwerx.JID.asJID(jid).getBareJID();delete this._pendingUnsubs[jid.toString()];delete this._pendingSubs[jid.toString()];var retVal=this.client.controllers.capabilities.removeFeatureFromJid(jid,'http://webex.com/connect/temp-presence+notify');var ent=this.client.entitySet.entity(jid);if(ent){if(ent instanceof jabberwerx.cisco.QuickContact){ent.remove();}else{delete ent.properties.temp_sub;if(ent.properties.subscription=="from"||ent.properties.subscription=="none"){ent.updatePresence(null);}
this.client.entitySet.event("entityUpdated").trigger(ent);}}
return retVal;},unsubscribeAll:function(jids){if(!jabberwerx.util.isArray(jids)){throw new TypeError("jids must be an array");}
for(var i=0;i<jids.length;++i){try{var tjid=jabberwerx.JID.asJID(jids[i]).getBareJIDString();}catch(ex){jabberwerx.util.debug.warn("Skipping "+jids[i]+", could not parse JID");continue;}
if(this._pendingSubs.hasOwnProperty(tjid)){delete this._pendingSubs[tjid];}
var entity=this.client.entitySet.entity(tjid);if(!entity||(entity.properties.temp_sub===undefined)){continue;}
if(this._pendingUnsubs.hasOwnProperty(tjid)){continue;}
this._pendingUnsubs[tjid]=true;}
if(!this._pendingTimer){this._processPending();}},removeEntity:function(entity){if(!(entity&&entity instanceof jabberwerx.cisco.QuickContact)){throw new TypeError("entity must be a quick contact");}
var jid=entity.jid;entity.destroy();this.unsubscribe(jid);},cleanupEntity:function(entity){this.client.controllers.capabilities.removeFeatureFromJid(entity.jid,'http://webex.com/connect/temp-presence+notify');entity.remove();},willBeSerialized:function(){if(this._pendingTimer!==undefined){clearInterval(this._pendingTimer);delete this._pendingTimer;}
this._super();},graphUnserialized:function(){this._super();this._checkTimer();},_handleStatusChange:function(evt){if(evt.data.next==jabberwerx.Client.status_disconnected){this._pendingSubs={};this._pendingUnsubs={};this._checkTimer();}},_presenceReceived:function(eventObj){var presence=jabberwerx.$(eventObj.selected);for(var i=0;i<presence.length;i++){if(presence[i]){var prs=jabberwerx.Stanza.createWithNode(presence[i]);var bareJidStr=prs.getFromJID().getBareJIDString();var entity=this.client.entitySet.entity(bareJidStr);if(!entity){entity=new jabberwerx.cisco.QuickContact(bareJidStr,this);this.client.entitySet.register(entity);}
entity.updatePresence(prs);}}
return true;},_handleResourcePresenceUpdate:function(eventObj){var presence=eventObj.data.presence;var nowAvailable=eventObj.data.nowAvailable;var jid=eventObj.data.fullJid;var entity=this.client.entitySet.entity(jid.getBareJID());if(entity&&entity instanceof(jabberwerx.RosterContact)&&entity.properties.subscription!="both"&&entity.properties.subscription!="to"&&nowAvailable){var p=this.client.getCurrentPresence().clone();var item=jabberwerx.$(p.getNode()).find("c[xmlns=http://jabber.org/protocol/caps]");item.remove();p.setTo(entity.jid.getBareJID());this.client.sendStanza(p);}
return false;},_handleEntityUpdated:function(eventObj){var entity=eventObj.data;if(entity.properties.temp_sub&&entity instanceof jabberwerx.RosterContact){if(entity.properties.subscription=="both"||entity.properties.subscription=="to"){this.unsubscribe(entity.jid);jabberwerx.util.debug.log("removing temp sub property from "+entity.jid);}else if(entity.properties.subscription=="from"){this.client.controllers.capabilities.addFeatureToJid(entity.jid,'http://webex.com/connect/temp-presence+notify');jabberwerx.util.debug.log("resending temp-presence+notify caps to "+entity.jid);}}
return false;},_handleEntityRemoved:function(eventObj){var entity=eventObj.data;if(entity.properties.temp_sub){if(this.client.isConnected()&&!(entity instanceof jabberwerx.cisco.QuickContact)){var quick=new jabberwerx.cisco.QuickContact(entity.jid,this);quick.apply(entity);this.client.entitySet.register(quick);this.subscribe(quick.jid);}else if(!this.client.isConnected()){this.unsubscribe(entity.jid);}}
return false;},_processPending:function(){var that=this;var queues=[{queue:this._pendingSubs,func:"subscribe"},{queue:this._pendingUnsubs,func:"unsubscribe"}];var currQueue=0;var sliceCounter=0;var totalSlices=Math.max(1,this.subscriptionSlice);while(sliceCounter<totalSlices&&currQueue<queues.length){for(var oneJID in queues[currQueue].queue){if(queues[currQueue].queue.hasOwnProperty(oneJID)){try{if(!this[queues[currQueue].func].apply(this,[oneJID])){jabberwerx.util.debug.warn(jabberwerx._("{0}({1}) returned false",queues[currQueue].func,oneJID));}}catch(ex){jabberwerx.util.debug.warn(jabberwerx._("{0}({1}) threw exception: {2}",queues[currQueue].func,oneJID,ex.message));}
if(++sliceCounter==totalSlices){break;}}}
currQueue++;}
delete this._pendingTimer;this._checkTimer();},_isEmpty:function(queue){for(var p in queue){if(queue.hasOwnProperty(p)){return false;}}
return true;},_checkTimer:function(){if(!this._isEmpty(this._pendingSubs)||!this._isEmpty(this._pendingUnsubs)){if(this._pendingTimer===undefined){var that=this;var timerTime=Math.max(0,this.subscriptionInterval)*1000;this._pendingTimer=setTimeout(function(){that._processPending();},timerTime);}}else if(this._pendingTimer){clearTimeout(this._pendingTimer);delete this._pendingTimer;}},_pendingSubs:{},_pendingUnsubs:{},_pendingTimer:undefined,subscriptionInterval:0.5,subscriptionSlice:10},"jabberwerx.cisco.QuickContactController");}})();
/*build/dist/VTG-CAXL-release-8.6.1/src/model/QuickContact.js*/

if(jabberwerx&&jabberwerx.cisco){jabberwerx.cisco.QuickContact=jabberwerx.Contact.extend({init:function(jid,quickContactCtrl){if(!(quickContactCtrl&&quickContactCtrl instanceof jabberwerx.cisco.QuickContactController)){throw new TypeError("quickContactCtrl must be provided and must be of type"+"jabberwerx.cisco.QuickContactController");}
this._super(jid,quickContactCtrl);this.properties.temp_sub=true;},_handleUnavailable:function(presence){var pres=this.getPrimaryPresence();if(!pres){this._insertPresence(presence);}else if(pres.getType()=="unavailable"){this._clearPresenceList();this._insertPresence(presence);}}},'jabberwerx.cisco.QuickContact');}